#include<stdio.h>
void put(char** a)
{
    for(int i = 0;i<6; i++)
    {
        printf("%s\n",a[i]);
    }
}
int main()
{
    char *a[6] = {"China","French","America","German","China","China"};
    put(a);
    return 0;
}
<background>
<starttime>
<year>2020</year>
<month>04</month>
<day>01</day>
<hour>00</hour>
<minute>00</minute>
<second>00</second>
</starttime>
<!--  This animation will start at midnight.  -->
<static>
<duration>1795.0</duration>
<file>/usr/share/backgrounds/Focal-Fossa_WP_4096x2304_GREY.png</file>
</static>
<transition>
<duration>5.0</duration>
<from>/usr/share/backgrounds/Focal-Fossa_WP_4096x2304_GREY.png</from>
<to>/usr/share/backgrounds/brad-huchteman-stone-mountain.jpg</to>
</transition>
<static>
<duration>1795.0</duration>
<file>/usr/share/backgrounds/brad-huchteman-stone-mountain.jpg</file>
</static>
<transition>
<duration>5.0</duration>
<from>/usr/share/backgrounds/brad-huchteman-stone-mountain.jpg</from>
<to>/usr/share/backgrounds/joshua-coleman-something-yellow.jpg</to>
</transition>
<static>
<duration>1795.0</duration>
<file>/usr/share/backgrounds/joshua-coleman-something-yellow.jpg</file>
</static>
<transition>
<duration>5.0</duration>
<from>/usr/share/backgrounds/joshua-coleman-something-yellow.jpg</from>
<to>/usr/share/backgrounds/matt-mcnulty-nyc-2nd-ave.jpg</to>
</transition>
<static>
<duration>1795.0</duration>
<file>/usr/share/backgrounds/matt-mcnulty-nyc-2nd-ave.jpg</file>
</static>
<transition>
<duration>5.0</duration>
<from>/usr/share/backgrounds/matt-mcnulty-nyc-2nd-ave.jpg</from>
<to>/usr/share/backgrounds/ryan-stone-skykomish-river.jpg</to>
</transition>
<static>
<duration>1795.0</duration>
<file>/usr/share/backgrounds/ryan-stone-skykomish-river.jpg</file>
</static>
<transition>
<duration>5.0</duration>
<from>/usr/share/backgrounds/ryan-stone-skykomish-river.jpg</from>
<to>/usr/share/backgrounds/hardy_wallpaper_uhd.png</to>
</transition>
<static>
<duration>1795.0</duration>
<file>/usr/share/backgrounds/hardy_wallpaper_uhd.png</file>
</static>
<transition>
<duration>5.0</duration>
<from>/usr/share/backgrounds/hardy_wallpaper_uhd.png</from>
<to>/usr/share/backgrounds/Focal-Fossa_WP_4096x2304_GREY.png</to>
</transition>
</background>